# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
   push:
    # Sequence of patterns matched against refs/heads
     branches:    
      - dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: A) Read Configuration
      shell: bash
      run: |
          ENV=${GITHUB_REF/refs\/heads\//}
          for NAME in ENV
          do echo "$NAME=${!NAME}" >> $GITHUB_ENV
          done
         
#     # Runs a single command using the runners shell
#     - name: Send greeting
#       shell: bash
#       run: echo ${{ secrets[format('DISTRIBUTION_ID_{0}', env.ENV)] }} BRANCH env.ENV
   
    - name: G) Invalidate CloudFront
      shell: bash
      run: aws cloudfront create-invalidation --distribution-id E1NK5WNQ5L043S --paths "/*"
#       run: aws --no-cli-pager --profile invalidate-cloudfront-action cloudfront create-invalidation --distribution-id E1NK5WNQ5L043S


